<?php
declare(strict_types=1);
namespace OCP\EventDispatcher { class Event {} interface IEventListener{public function handle(Event $event):void;} }
namespace OCA\FlzPermissionMatrix\PublicApi\V1 {
 interface PermissionProvider{public function descriptor():PermissionProviderDescriptor;public function collect():PermissionProviderResult;} final class PermissionProviderDescriptor{public function __construct(...$a){}} final class PermissionCondition{private function __construct(public string $operator,public ?string $groupId=null,public array $children=[]){}public static function group(string $id):self{return new self('group',$id);}public static function all(array $children):self{return new self('all',null,$children);}public static function nextcloudAdmin():self{return new self('nextcloud-admin');}public static function temporaryAppAdminGrant():self{return new self('app-admin-grant');}} final class PermissionRule{public function __construct(public string $type,public string $name,public string $detail,public string $permission,public string $label,public string $effect,public string $scope,public PermissionCondition $condition,public string $source,public string $confidence){}} final class PermissionProviderResult{public function __construct(public array $rules,public bool $complete=true,public array $warnings=[]){}} final class RegisterPermissionProvidersEvent extends \OCP\EventDispatcher\Event{public array $providers=[];public function register(PermissionProvider $p):void{$this->providers[]=$p;}}
}
namespace {
 use OCA\BrTop\Permission\BrTopPermissionProvider;use OCA\BrTop\Permission\BrTopPermissionProviderListener;use OCA\BrTop\Permission\BrTopPermissionSourceInterface;use OCA\FlzPermissionMatrix\PublicApi\V1\RegisterPermissionProvidersEvent;
 $source=new class implements BrTopPermissionSourceInterface{public function memberGroupId():string{return 'br-members';}};$provider=new BrTopPermissionProvider($source);$rules=$provider->collect()->rules;$member=[];$admin=[];foreach($rules as $rule){if($rule->condition->operator==='group')$member[$rule->permission]=$rule;if($rule->condition->operator==='all')$admin[$rule->permission]=$rule;}
 foreach(['brtop.session.manage','brtop.document.generate'] as $key)if(($member[$key]->condition->groupId??null)!=='br-members')throw new RuntimeException('Mitgliederrecht fehlt: '.$key);
 foreach(['brtop.settings.manage','brtop.legislature.manage','brtop.absence.confirm'] as $key)if(!isset($admin[$key]))throw new RuntimeException('Adminrecht fehlt: '.$key);
 $grantManagement=array_values(array_filter($rules,fn($rule)=>$rule->permission==='brtop.admin_access.manage'))[0]??null;if(($grantManagement?->condition->operator)!=='group'||($grantManagement?->condition->groupId)!=='Datenschutzbeauftragte')throw new RuntimeException('Datenschutzrollen-Projektion für Freigabesteuerung fehlt.');
 foreach($admin as $rule)if(array_map(fn($condition)=>$condition->operator,$rule->condition->children)!==['nextcloud-admin','app-admin-grant'])throw new RuntimeException('Adminrecht verlangt nicht native Administration und aktive App-Freigabe.');
 if(!str_contains($member['brtop.document.generate']->detail,'nicht untersucht'))throw new RuntimeException('Der Ausschluss von Dateiinhalten muss sichtbar bleiben.');
 $event=new RegisterPermissionProvidersEvent();$listener=new BrTopPermissionProviderListener($provider);if(!$listener instanceof \OCP\EventDispatcher\IEventListener)throw new RuntimeException('Permission-Listener erfüllt den Nextcloud-Eventvertrag nicht.');$listener->handle($event);if(($event->providers[0]??null)!==$provider)throw new RuntimeException('Lazy-Registrierung fehlt.');echo "BRTop permission provider tests passed\n";
}
