<?php
declare(strict_types=1);
namespace OCP{interface IRequest{}interface IUser{public function getUID():string;}interface IUserSession{public function getUser():?IUser;}}
namespace OCA\BrTop\AppInfo{final class Application{public const APP_ID='brtop';}}
namespace OCP\AppFramework{class Controller{public function __construct(string $appId,\OCP\IRequest $request){}}final class Http{public const STATUS_FORBIDDEN=403;}}
namespace OCP\AppFramework\Http{final class TemplateResponse{public function __construct(public string $app,public string $template,public array $params=[],public string $renderAs='',public int $status=200){}}}
namespace OCP\AppFramework\Http\Attribute{#[\Attribute(\Attribute::TARGET_METHOD)]final class NoCSRFRequired{}#[\Attribute(\Attribute::TARGET_METHOD)]final class NoAdminRequired{}}
namespace OCA\BrTop\Service{final class BrAccessService{public function __construct(public bool $allowed){}public function canUse(string $uid):bool{return$this->allowed;}}final class TemporaryAdminAccessService{public function __construct(public bool $manage,public bool $needsGrant){}public function canManage():bool{return$this->manage;}public function currentAdminNeedsGrant():bool{return$this->needsGrant;}}}
namespace{use OCA\BrTop\Controller\PageController;use OCA\BrTop\Service\BrAccessService;use OCA\BrTop\Service\TemporaryAdminAccessService;$request=new class implements OCP\IRequest{};$user=new class implements OCP\IUser{public function getUID():string{return'actor';}};$session=new class($user)implements OCP\IUserSession{public function __construct(private ?OCP\IUser $user){}public function getUser():?OCP\IUser{return$this->user;}};$response=(new PageController($request,$session,new BrAccessService(false),new TemporaryAdminAccessService(true,false)))->index();if($response->app!=='brtop'||$response->params['canManageAdminAccess']!==true||$response->params['hasBrTopAccess']!==false)throw new RuntimeException('DPO ohne Fachrolle erhält keine isolierte Steuerung.');$response=(new PageController($request,$session,new BrAccessService(false),new TemporaryAdminAccessService(false,true)))->index();if($response->app!=='brtop'||$response->params['showAdminAccessLink']!==false)throw new RuntimeException('Admin ohne DPO erhielt Direktlink.');$response=(new PageController($request,$session,new BrAccessService(false),new TemporaryAdminAccessService(true,true)))->index();if($response->params['showAdminAccessLink']!==true)throw new RuntimeException('Admin+DPO erhielt keinen Direktlink.');$response=(new PageController($request,$session,new BrAccessService(true),new TemporaryAdminAccessService(false,false)))->index();if($response->params['hasBrTopAccess']!==true)throw new RuntimeException('BRTop-berechtigtes Konto erhielt Fachoberfläche nicht.');$response=(new PageController($request,$session,new BrAccessService(false),new TemporaryAdminAccessService(false,false)))->index();if($response->app!=='core'||$response->status!==403)throw new RuntimeException('Gewöhnliches Konto blieb nicht geschützt.');echo "BRTop page controller role projection tests passed\n";}
