(function() {
    function createController(byId) {
        function defaultResolutionKind(type) {
            if (type === 'personnel_99') {
                return 'consent_refusal';
            }
            if (type === 'personnel_100') {
                return 'urgency_dispute';
            }
            if (type === 'personnel_102') {
                return 'dismissal_objection';
            }
            if (type === 'protocol') {
                return 'protocol_approval';
            }
            return 'approval_general';
        }

        function defaultAgendaKind(type) {
            if (type === 'consultation_report') {
                return 'report';
            }
            if (type === 'personnel') {
                return 'section';
            }
            return 'discussion';
        }

        function buildResolutionQuestion(kind, type, measure) {
            const m = (measure || 'die Maßnahme').trim();

            if (kind === 'consent_refusal') {
                return `Wer verweigert die Zustimmung zu ${m} und widerspricht ihr damit?`;
            }

            if (kind === 'urgency_dispute') {
                return `Wer bestreitet, dass die vorläufige Durchführung der personellen Maßnahme ${m} aus sachlichen Gründen dringend erforderlich ist?`;
            }

            if (kind === 'dismissal_objection') {
                return `Wer widerspricht der beabsichtigten Kündigung ${m} gemäß § 102 BetrVG?`;
            }

            return `Wer stimmt ${m} zu?`;
        }

        function usesPersonnelContext(type) {
            return ['personnel_99', 'personnel_100', 'personnel_102'].includes(type);
        }

        function isResolutionSelected() {
            return byId('top-requires-resolution').checked;
        }

        function setFieldVisible(id, visible) {
            byId(id).hidden = !visible;
        }

        function setResolutionQuestion(force = false) {
            const checkbox = byId('top-requires-resolution');
            const kind = byId('top-resolution-kind');
            const subject = byId('top-subject');
            const resolution = byId('top-resolution');
            const type = byId('top-type');

            if (!checkbox.checked) {
                return;
            }

            const isAuto = resolution.dataset.autoGenerated !== '0';
            if (force || isAuto || resolution.value.trim() === '') {
                const count = Math.max(1, Number(byId('top-resolution-count').value || 1));
                const questions = [buildResolutionQuestion(kind.value, type.value, subject.value)];
                while (questions.length < count) {
                    questions.push(`Beschlussfrage ${questions.length + 1} ergänzen.`);
                }
                resolution.value = questions.join('\n');
                resolution.dataset.autoGenerated = '1';
            }
        }

        function refreshContext() {
            const type = byId('top-type').value;
            const resolutionSelected = isResolutionSelected();
            const personnelSelected = usesPersonnelContext(type);

            setFieldVisible('top-person-field', personnelSelected);
            setFieldVisible('top-legal-field', personnelSelected || resolutionSelected);
            setFieldVisible('top-resolution-options', resolutionSelected);

            if (!resolutionSelected) {
                byId('top-resolution').dataset.autoGenerated = '1';
            }
        }

        function updateResolutionDefault() {
            const type = byId('top-type').value;
            const legal = byId('top-legal');
            const kind = byId('top-resolution-kind');
            const agendaKind = byId('top-agenda-kind');

            agendaKind.value = defaultAgendaKind(type);
            kind.value = defaultResolutionKind(type);

            if (type === 'personnel_99') {
                legal.value = '§ 99 BetrVG';
            } else if (type === 'personnel_100') {
                legal.value = '§ 100 BetrVG';
            } else if (type === 'personnel_102') {
                legal.value = '§ 102 BetrVG';
            } else if (['§ 99 BetrVG', '§ 100 BetrVG', '§ 102 BetrVG'].includes(legal.value)) {
                legal.value = '';
            }

            setResolutionQuestion(true);
            refreshContext();
        }

        function show() {
            refreshContext();
            byId('top-form-panel').hidden = false;
            byId('show-top-form').setAttribute('aria-expanded', 'true');
        }

        function hide() {
            byId('top-form-panel').hidden = true;
            byId('show-top-form').setAttribute('aria-expanded', 'false');
        }

        function clear() {
            byId('top-subject').value = '';
            byId('top-person').value = '';
            byId('top-legal').value = '';
            byId('top-resolution').value = '';
            byId('top-invitation-note').value = '';
            byId('top-attachments').value = '';
            byId('top-resolution-count').value = '1';
            byId('top-requires-resolution').checked = false;
            byId('top-protocol-content').value = '';
            byId('top-resolution').dataset.autoGenerated = '1';
            updateResolutionDefault();
        }

        function payload() {
            const type = byId('top-type').value;
            const resolutionSelected = isResolutionSelected();
            const resolutionCount = resolutionSelected ? Math.max(1, Number(byId('top-resolution-count').value || 1)) : 0;
            const personnelSelected = usesPersonnelContext(type);
            const legalSelected = personnelSelected || resolutionSelected;

            return {
                type,
                parentId: 0,
                agendaItemKind: byId('top-agenda-kind').value,
                subject: byId('top-subject').value,
                personName: personnelSelected ? byId('top-person').value : '',
                legalBasis: legalSelected ? byId('top-legal').value : '',
                resolutionText: resolutionSelected ? byId('top-resolution').value : '',
                requiresResolution: resolutionSelected,
                resolutionCount,
                invitationNote: byId('top-invitation-note').value,
                attachmentPaths: byId('top-attachments').value,
                protocolContent: byId('top-protocol-content').value
            };
        }

        function init() {
            byId('show-top-form').addEventListener('click', show);
            byId('hide-top-form').addEventListener('click', hide);
            byId('top-type').addEventListener('change', updateResolutionDefault);
            byId('top-subject').addEventListener('input', () => setResolutionQuestion(false));
            byId('top-resolution-kind').addEventListener('change', () => setResolutionQuestion(true));
            byId('top-agenda-kind').addEventListener('change', () => {
                setResolutionQuestion(true);
                refreshContext();
            });
            byId('top-requires-resolution').addEventListener('change', () => {
                const box = byId('top-requires-resolution');
                if (box.checked) {
                    byId('top-resolution-count').value = Math.max(1, Number(byId('top-resolution-count').value || 1));
                }
                setResolutionQuestion(false);
                refreshContext();
            });
            byId('top-resolution-count').addEventListener('input', () => {
                if (Number(byId('top-resolution-count').value || 0) < 1) {
                    byId('top-resolution-count').value = '1';
                }
                setResolutionQuestion(false);
            });
            byId('top-resolution').addEventListener('input', () => {
                byId('top-resolution').dataset.autoGenerated = '0';
            });

            updateResolutionDefault();
        }

        return {
            init,
            show,
            hide,
            clear,
            payload
        };
    }

    window.BRTop = window.BRTop || {};
    window.BRTop.topForm = { createController };
})();
